# Copyright (c) 2017 The Tencent Authors. All rights reserved.

set(IS_IOS FALSE)
set(IS_MAC FALSE)
set(IS_ANDROID FALSE)
set(IS_WINDOWS FALSE)
set(ARCH_IS_ARMV7 FALSE)
set(ARCH_IS_ARM64 FALSE)
set(ARCH_IS_X86 FALSE)
set(ARCH_IS_X64 FALSE)
if(${CMAKE_SYSTEM_NAME} STREQUAL "Android")
    set(IS_ANDROID TRUE)
    set(ANDROID_ABI ${CMAKE_ANDROID_ARCH_ABI})
    if(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "armeabi-v7a")
        set(ARCH_IS_ARMV7 TRUE)
    elseif(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "arm64-v8a")
        set(ARCH_IS_ARM64 TRUE)
    elseif(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "x86")
        set(ARCH_IS_X86 TRUE)
    elseif(${CMAKE_ANDROID_ARCH_ABI} STREQUAL "x86_64")
        set(ARCH_IS_X64 TRUE)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    if(IOS)
        set(IS_IOS TRUE)
    else()
        set(IS_MAC TRUE)
    endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    set(IS_WINDOWS TRUE)
endif()